parameters:
#    pizz_client.example.class: Pizz\ClientBundle\Example

services:
#    pizz_client.example:
#        class: %pizz_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
