<?php

namespace Pizz\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PizzaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaRepository extends EntityRepository
{
}
