<?php

namespace Pizz\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIngredientRepository extends EntityRepository
{
}
