<?php

namespace Pizz\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CBRepository extends EntityRepository
{
}
