parameters:
#    pizz_admin.example.class: Pizz\AdminBundle\Example

services:
#    pizz_admin.example:
#        class: %pizz_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
