parameters:
#    pizz_user.example.class: Pizz\UserBundle\Example

services:
#    pizz_user.example:
#        class: %pizz_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
